name: Metadata

on:
  workflow_call:
    inputs:
      coreName:
        description: The core (most minimal) name of the project
        type: string
        required: false
      strictVersion:
        description: Error if version not valid?
        type: boolean
        default: false

    outputs:
      project:
        description: Project name
        value: ${{ jobs.name.outputs.project }}
      coreName:
        description: Minimal project name
        value: ${{ jobs.name.outputs.core }}
      textVersion:
        description: Full version number (with v prefix)
        value: ${{ jobs.version.outputs.text }}
      numericVersion:
        description: Full version number (with no v prefix)
        value: ${{ jobs.version.outputs.numeric }}
      majorVersion:
        description: Just the first portion of the version number
        value: ${{ jobs.version.outputs.major }}
      significantVersion:
        description: All of the significant parts of the version number
        value: ${{ jobs.version.outputs.significant }}
      currentBranch:
        description: Name of the current branch of the project
        value: ${{ jobs.meta.outputs.currentBranch }}
      homepage:
        description: Project homepage
        value: ${{ jobs.meta.outputs.homepage }}
      topics:
        description: Project topics
        value: ${{ jobs.meta.outputs.topics }}
      linuxName:
        description: Name that would be given to a library for this project on Linux
        value: ${{ jobs.meta.outputs.linuxName }}
      macName:
        description: Name that would be given to a library for this project on MacOS
        value: ${{ jobs.meta.outputs.macName }}
      winName:
        description: Filename that would be given to a DLL for this project on Windows
        value: ${{ jobs.meta.outputs.winName }}

jobs:
  name:
    name: Determine Name
    uses: ./.github/workflows/name.yaml
    with:
      coreName: ${{ inputs.coreName }}

  version:
    name: Determine Version
    uses: ./.github/workflows/version.yaml

  meta:
    name: Metadata
    runs-on: ubuntu-latest
    needs: [ name, version ]
    outputs:
      currentBranch: ${{ steps.branch.outputs.currentBranch }}
      homepage: ${{ steps.url.outputs.homepage }}
      topics: ${{ steps.topics.outputs.topics }}
      linuxName: lib${{ needs.name.outputs.coreName }}.so.${{ needs.version.outputs.significant }}
      macName: lib${{ needs.name.outputs.coreName }}.${{ needs.version.outputs.significant }}.dylib
      winName: ${{ needs.name.outputs.coreName }}-${{ needs.version.outputs.significant }}.dll

    steps:
      - name: Dump GitHub context
        if: false
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get Branch
        id: branch
        run: |
          currentBranch=${GITHUB_REF#refs/heads/}
          echo Branches current $currentBranch default $defaultBranch
          if [[ $currentBranch == refs/tags/* ]] ; then
            currentBranch=$defaultBranch
          fi
          echo "::set-output name=currentBranch::$currentBranch"
        env:
          defaultBranch: ${{ github.event.repository.default_branch }}

      - name: Homepage
        id: url
        run: |
          if [ "$homepage" == "" ] ; then
            homepage="$htmlUrl"
          fi
          if [ "$homepage" == "" ] ; then
            homepage="https://stirlinglabs.com"
          fi
          echo "::set-output name=homepage::$homepage"
        env:
          homepage: ${{ github.event.repository.homepage }}
          htmlUrl: ${{ github.event.repository.html_url }}

      - name: Topics
        id: topics
        run: |
          topicsArray=$(echo $topics | jq -r '.[]')
          topics=""
          space=""
          for topic in "${topicsArray[@]}" ; do
            topics="$topics$space$topic"
            space=" "
          done
          echo "::set-output name=topics::$topics"
        env:
          topics: ${{ toJSON(github.event.repository.topics) }}
