name: Metadata

on:
  workflow_call:
    inputs:
      repo:
        description: The 'owner/repo' string of the repository to be processed
        type: string
        default: ${{ github.repository }}
      ref:
        description: The git reference of the commit to be processed
        type: string
        default: ${{ github.ref }} # perhaps ref_name & ref_type instead?
      coreName:
        description: The core (most minimal) name of the project
        type: string
        required: false
      strictVersion:
        description: Error if version not valid?
        type: boolean
        default: false

    outputs:
      project:
        description: Project name
        value: ${{ jobs.name.outputs.project }}
      coreName:
        description: Minimal project name
        value: ${{ jobs.name.outputs.core }}
      textVersion:
        description: Full version number (with v prefix)
        value: ${{ jobs.version.outputs.text }}
      numericVersion:
        description: Full version number (with no v prefix)
        value: ${{ jobs.version.outputs.numeric }}
      majorVersion:
        description: Just the first portion of the version number
        value: ${{ jobs.version.outputs.major }}
      significantVersion:
        description: All of the significant parts of the version number
        value: ${{ jobs.version.outputs.significant }}
      tripleVersion:
        description: The dotted triple that makes up traditional versioning
        value: ${{ jobs.version.outputs.triple }}
      currentBranch:
        description: Name of the current branch of the project
        value: ${{ jobs.meta.outputs.currentBranch }}
      homepage:
        description: Project homepage
        value: ${{ jobs.meta.outputs.homepage }}
      description:
        description: Project description
        value: ${{ jobs.meta.outputs.description }}
      topics:
        description: Project topics in JSON array
        value: ${{ jobs.meta.outputs.topicsJson }}
      linuxName:
        description: Name that would be given to a library for this project on Linux
        value: ${{ jobs.meta.outputs.linuxName }}
      macName:
        description: Name that would be given to a library for this project on MacOS
        value: ${{ jobs.meta.outputs.macName }}
      winName:
        description: Filename that would be given to a DLL for this project on Windows
        value: ${{ jobs.meta.outputs.winName }}

jobs:
  name:
    name: Determine Name
    uses: ./.github/workflows/name.yaml
    with:
      coreName: ${{ inputs.coreName }}

  version:
    name: Determine Version
    uses: ./.github/workflows/version.yaml

  meta:
    name: Metadata
    runs-on: ubuntu-latest
    needs: [ name, version ]
    outputs:
      currentBranch: ${{ steps.branch.outputs.currentBranch }}
      homepage: ${{ steps.url.outputs.homepage }}
      description: ${{ steps.meta.outputs.description }}
      topics: ${{ steps.api.outputs.topics }}
      linuxName: lib${{ needs.name.outputs.coreName }}.so.${{ needs.version.outputs.significant }}
      macName: lib${{ needs.name.outputs.coreName }}.${{ needs.version.outputs.significant }}.dylib
      winName: ${{ needs.name.outputs.coreName }}-${{ needs.version.outputs.significant }}.dll

    steps:
      - name: Dump GitHub context
        if: false
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Set Variables
        id: api
        env:
          repo: ${{ inputs.repo }}
          defaultBranch: ${{ github.event.repository.default_branch }}
          homepage: ${{ github.event.repository.homepage }}
          htmlUrl: ${{ github.event.repository.html_url }}
          topics: ${{ toJSON(github.event.repository.topics) }}
        run: |
          # init
          url="https://api.github.com/repos/${repo}"
          echo "url=${url}" >> $GITHUB_OUTPUT
          json=""
          # Define function
          updateValue() {
            [[ "$1" != "" ]] && _var="$1" || exit 1
            [[ "$2" != "" ]] && _term="$2" || _term="$1"
            # if the value is an empty string or empty array
            if [[ "${!_var}" =~ "^$|\[[[:space:]]*\]" ]] ; then
              [[ "$json" == "" ]] && json=$(curl -s $url);
              read "${_var}" <<< $(jq -r ".${_term}" <<< "$json")
            fi
            echo "${_var}=${!_var}" >> $GITHUB_OUTPUT
          }
          # Do work
          updateValue "defaultBranch" "default_branch"
          updateValue "homepage"
          updateValue "htmlUrl" "html_url"
          updateValue "topics"
          updateValue "description"

      - name: Get Branch
        id: branch
        run: |
          currentBranch=${GITHUB_REF#refs/heads/}
          echo Branches current $currentBranch default $defaultBranch
          if [[ $currentBranch == refs/tags/* ]] ; then
            currentBranch=$defaultBranch
          fi
          echo "currentBranch=${currentBranch}" >> $GITHUB_OUTPUT
        env:
          defaultBranch: ${{ steps.api.outputs.defaultBranch }}

      - name: Homepage
        id: url
        env:
          homepage: ${{ steps.api.outputs.homepage }}
          htmlUrl: ${{ steps.api.outputs.htmlUrl }}
        run: |
          if [ "$homepage" == "" ] ; then
            homepage="$htmlUrl"
          fi
          if [ "$homepage" == "" ] ; then
            homepage="https://stirlinglabs.com"
          fi
          echo "homepage=${homepage}" >> $GITHUB_OUTPUT
