name: NuPkg Release Check

on:
  workflow_call:
    inputs:
      upstream:
        description: Project owner/name (the path part of a GitHub repo URL)
        type: string
        required: false
        default: ${{ github.repository }}
      rids:
        description: Runtime identifiers for the platforms to test in a simple list (space separated)
        type: string
        default: 'linux-x64 osx win-x64'
      releasePrefix:
        description: Irrelevant prefix to ignore before the release version number (e.g. 'v')
        type: string
        required: false
      ignoreReleases:
        description: Simple list of version numbers to ignore (space separated)
        type: string
        required: false
      nupkgName:
        description: The package name to test (with the text 'RID' in place of the RID), e.g. StirlingLabs.project.RID.suffix
        type: string
        required: true
      forceVersion:
        description: Force a specific version number to be tested & released
        type: string
        required: false

    outputs:
      releasesNeeded:
        description: JSON array of the version numbers that do not have all of the required packages (i.e. one for each RID)
        value: ${{ jobs.check.outputs.releasesNeeded }}
      continue:
        description: Boolean value; true if there are releases needed
        value: ${{ jobs.check.outputs.continue }}
      githubApiUrl:
        description: GitHub API base URL for the repo
        value: ${{ jobs.check.outputs.githubApi }}
      releasesUrl:
        description: GitHub API URL to list all releases for the repo
        value: ${{ jobs.check.outputs.releasesUrl }}
      tagsUrl:
        description: GitHub API URL to list all tags for the repo
        value: ${{ jobs.check.outputs.tagsUrl }}
      tagUrl:
        description: GitHub API URL to list details of a specific tag in the repo (append the tag name)
        value: ${{ jobs.check.outputs.tagUrl }}
      gitUrl:
        description: GitHub project git URL
        value: ${{ jobs.check.outputs.gitUrl }}
      platformArray:
        description: Platform identifiers of the platforms required in a JSON array
        value: ${{ jobs.check.outputs.platformArray }}
      ridArray:
        description: Runtime identifiers of the platforms tested in a JSON array
        value: ${{ jobs.check.outputs.ridArray }}
      rids:
        description: Runtime identifiers from input in a simple list
        value: ${{ inputs.rids }}
      upstream:
        description:  Project owner/name (like GitHub repo URL) provided as input
        value: ${{ inputs.upstream }}
      releasePrefix:
        description: Irrelevant prefix to ignore before the release version number (e.g. 'v') provided as input
        value: ${{ inputs.releasePrefix }}

jobs:
  check:
    name: Status
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    outputs:
      releasesNeeded: ${{ steps.requirements.outputs.releasesNeeded }}
      continue: ${{ steps.requirements.outputs.continue }}
      githubApi: ${{ steps.github.outputs.githubApi }}
      releasesUrl: ${{ steps.github.outputs.releasesUrl }}
      tagsUrl: ${{ steps.github.outputs.tagsUrl }}
      tagUrl: ${{ steps.github.outputs.tagUrl }}
      gitUrl: ${{ steps.github.outputs.gitUrl }}
      ridArray: ${{ steps.arrays.outputs.ridArray }}
      platformArray: ${{ steps.arrays.outputs.platformArray }}
    steps:
      - name: GitHub Release List
        id: github
        env:
          upstream: ${{ inputs.upstream }}
          releasePrefix: ${{ inputs.releasePrefix }}
          ignoreReleases: ${{ inputs.ignoreReleases }}
          forceVersion: ${{ inputs.forceVersion }}
        run: |
          # GitHub info
          releasesUrl="https://api.github.com/repos/${upstream}/releases"
          # Make these URLs available for other scripts
          #shellcheck disable=SC2129
          echo "releasesUrl=${releasesUrl}" >> "$GITHUB_OUTPUT"
          echo "githubApi=https://api.github.com/repos/${upstream}" >> "$GITHUB_OUTPUT"
          echo "tagsUrl=https://api.github.com/repos/${upstream}/tags" >> "$GITHUB_OUTPUT"
          echo "tagUrl=https://api.github.com/repos/${upstream}/git/ref/tags/" >> "$GITHUB_OUTPUT"
          echo "gitUrl=git://github.com/${upstream}.git" >> "$GITHUB_OUTPUT"
          if [[ "$forceVersion" != "" ]] ; then
            echo "‼️ Forcing version ${forceVersion}"
            echo "validReleaseList=\"${forceVersion}\"" >> "$GITHUB_OUTPUT"
            echo "continue=true" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          # Get release data
          if ! json="$(curl -s "${releasesUrl}")" ; then
            echo -e "Failed to get release data from $releasesUrl:\n$json"
            #exit 1
          fi
          if ! releasesJson="$(jq -c . <<< "$json")" ; then
            echo -e "Failed to parse json from $releasesUrl:\n$releasesJson\njson:\n$json"
            #exit 1
          fi
          if ! releaseList="$(jq -r ".[].tag_name" <<< "$releasesJson")" ; then
            echo -e "Failed to parse releaseList from releasesJson:\n$releaseList\nreleasesJson:\n$releasesJson"
            #exit 1
          fi
          echo "releases:"
          mapfile -t releaseArray <<< "$releaseList"
          validReleaseList="[ " && validReleaseListComma=""
          for release in "${releaseArray[@]}" ; do
            # Skip releases in the ignore list
            version=${release#"$releasePrefix"}
            #echo "- Checking ${release} == ${version}"
            if [[ "${ignoreReleases}" != *"\"${version}\""* ]] && \
               [[ "${ignoreReleases}" != *" ${version} "* ]] && \
               [[ "${ignoreReleases}" != *"\"${release}\""* ]] && \
               [[ "${ignoreReleases}" != *" ${release} "* ]]
            then
              validReleaseList="${validReleaseList}${validReleaseListComma}\"${version}\""
              validReleaseListComma=", "
              echo "- ${release} added"
            else
              echo "- ${release} ignored"
            fi
          done
          validReleaseList="${validReleaseList} ]"
          if echo "$validReleaseList" | jq -c '[.[]]' ; then
            echo "continue=true" >> "$GITHUB_OUTPUT"
          else
            echo "continue=false" >> "$GITHUB_OUTPUT"
          fi
          echo "release_json=${validReleaseList}" >> "$GITHUB_OUTPUT"

      - name: NuGet Package List
        id: nuget
        if: ${{ steps.github.outputs.continue == 'true' }}
        env:
          rids: ${{ inputs.rids }}
          nupkgName: ${{ inputs.nupkgName }}
        run: |
          # Gather NuGet release info
          main() {
            if [[ "$nupkgName" == *".RID."* ]] && [[ "$rids" != "" ]] ; then
              # Check if all RIDs have packages for each version
              echo "RID-specific NuGet package $nupkgName -> $rids"
              pkgVersionJson="[ " && pkgVersionJsonComma=""
              mapfile -t -d ' ' rids <<< "$rids"
              for rid in "${rids[@]}" ; do
                nupkg="${nupkgName/.RID./".${rid}."}"
                echo "Getting list for $nupkg"
                versionJson="$(getPackageVersionJson "$nupkg")"
                echo "NuGet has: ${versionJson}"
                if ! versionList="$(jq -r '.[]' <<< "$versionJson")" ; then
                  echo "Error: Failed to convert $versionJson into bash array: $versionArray"
                  #exit 1
                fi
                echo "Mapping $versionList"
                mapfile -t versionArray <<< "$versionList"
                for version in "${versionArray[@]}" ; do
                  quotedVersion="\"${version}\""
                  if [[ "$pkgVersionJson" == *"quotedVersion"* ]] ; then
                    echo "Skipping duplicate $version $quotedVersion is in $pkgVersionJson"
                    continue
                  else
                    echo "Adding $quotedVersion"
                  fi
                  pkgVersionJson="${pkgVersionJson}${pkgVersionJsonComma}${quotedVersion}"
                  pkgVersionJsonComma=", "
                done
              done
              pkgVersionJson="${pkgVersionJson} ]"    
            else
              echo "Getting list for $nupkgName"
              pkgVersionJson="$(getPackageVersionJson "$nupkgName")"
            fi
            if echo "$pkgVersionJson" | jq -r '[.[]]' ; then
              echo "continue=true" >> "$GITHUB_OUTPUT"
            else
              echo "continue=false" >> "$GITHUB_OUTPUT"
            fi
            echo "version_json=${pkgVersionJson}" >> "$GITHUB_OUTPUT"
          }
          
          function getPackageVersionJson() {
            local pkg="$1" ; local url ; local response ; local json
            [[ "$pkg" == "$1" ]] && echo "searching for $pkg" >&2
            [[ "$pkg" == "" ]] && echo "Error: No package name provided" >&2 && exit 1
            url="https://api.nuget.org/v3-flatcontainer/${pkg}/index.json"
            if ! response="$( curl -s "$url" )" ; then
              echo -e "Problem while getting ${url}\n${response}" >&2
              exit 1
            fi
            if [[ "$response" == *"BlobNotFound"* ]] ; then
              echo -e "Could not find $pkg at $url\n$response" >&2
              return
            fi
            if [[ "$response" == *"Error"* ]] ; then
              echo -e "Problem while processing ${pkg} at ${url}:\n${response}\n" >&2
              exit 1
            fi
            if ! json="$(jq -c '[.versions|sort|to_entries[]|(.value)]' <<< "$response")" ; then
              echo -e "Problem while processing ${response}\n${json}\n" >&2
              exit 1
            fi
            echo "$json"
          }
          main "$@" ; exit $?

      - name: Determine Requirements
        id: requirements
        if: ${{ steps.nuget.outputs.continue == 'true' }}
        env:
          releasePrefix: ${{ inputs.releasePrefix }}
          nugetVersionJson: ${{ steps.nuget.outputs.version_json }}
          githubReleaseJson: ${{ steps.github.outputs.release_json }}
        run: |
          #
          # From the above, prepare a list of releases that do not have all of the required packages
          echo "Retrieving data"
          if ! nugetVersions="$(echo "$nugetVersionJson" | jq -r '.[]')" ; then
            echo "Error: Failed to convert $nugetVersionJson into bash array: $nugetVersions"
            exit 1
          fi
          if ! githubReleases="$(echo "$githubReleaseJson" | jq -r '.[]')" ; then
            echo "Error: Failed to convert $githubReleaseJson into bash array: $githubReleases"
            exit 1
          fi

          mapfile -t -d ' ' nugetVersions <<< "$nugetVersions"
          mapfile -t -d ' ' githubReleases <<< "$githubReleases"

          echo "Determining requirements"
          releasesNeededJson="[ " ; releasesNeededJsonDelim="" ; releasesNeeded="" ; releasesNeededDelim=""
          for release in "${githubReleases[@]}" ; do
            if [[ "$release" != *"\""* ]] ; then
              quotedRelease="\"${release}\""
              echo "Quoting release"
            else
              quotedRelease="${release}"
            fi
            echo "Testing if ${quotedRelease} is in ${nugetVersions[*]}"
            if [[ "${nugetVersions[*]}" != *"${quotedRelease}"* ]] ; then
              echo "Need ${release}"
              releasesNeededJson="${releasesNeededJson}${releasesNeededJsonDelim}\"${release}\""
              releasesNeeded="${releasesNeeded}${releasesNeededDelim}\"${release}\""
              releasesNeededJsonDelim=", " ; releasesNeededDelim=" "
            else
              echo "Have ${release} ~ ${nugetVersions[*]}"
            fi
          done
          releasesNeededJson="${releasesNeededJson} ]"

          echo "Writing output"
          if echo "$releasesNeededJson" | jq -c '[.[]]' ; then
            echo "continue=true" >> "$GITHUB_OUTPUT"
          else
            echo "continue=false" >> "$GITHUB_OUTPUT"
          fi
          echo "releasesNeeded=${releasesNeeded}" >> "$GITHUB_OUTPUT"
          echo "releases_needed_json=${releasesNeededJson}" >> "$GITHUB_OUTPUT"
          echo -e "Releases needed: ${releasesNeededJson}"

      - name: Arrays
        id: arrays
        if: ${{ steps.requirements.outputs.continue == 'true' }}
        env:
          rids: ${{ inputs.rids }}
        run: |
          ridArray="[ " && ridArrayComma=""
          platformArray="[ " && platformArrayComma=""
          for rid in $rids ; do
            ridArray="${ridArray}${ridArrayComma}\"${rid}\""
            ridArrayComma=", "
            case "$rid" in
              "linux-x64") platform="ubuntu-latest" ;;
              "osx") platform="macos-latest" ;;
              "win-x64") platform="windows-latest" ;;
              *) platform="ubuntu-latest" ;;
            esac
            platformArray="${platformArray}${platformArrayComma}\"${platform}\""
            platformArrayComma=", "
          done
          ridArray="${ridArray} ]"
          platformArray="${platformArray} ]"
          echo "ridArray=$ridArray" >> "$GITHUB_OUTPUT"
          echo "platformArray=$platformArray" >> "$GITHUB_OUTPUT"
          #end
