name: Version

on:
  workflow_call:
    inputs:
      version:
        description: Version of this release
        type: string
        required: false
      strict:
        description: Error if the version number is invalid
        type: boolean
        default: true

    outputs:
      text:
        description: Full dotted version number (with v prefix)
        value: ${{ jobs.version.outputs.text }}
      numeric:
        description: Full dotted version number (with no v prefix)
        value: ${{ jobs.version.outputs.numeric }}
      major:
        description: Just the first number from the version
        value: ${{ jobs.version.outputs.major }}
      significant:
        description: The significant digits of the version number
        value: ${{ jobs.version.outputs.significant }}
      triple:
        description: The first 3 significant digits of the version
        value: ${{ jobs.version.outputs.triple }}
      preRelease:
        description: Boolean, true if version is pre-release
        value: ${{ jobs.version.outputs.preRelease }}

jobs:
  version:
    name: Get Version
    runs-on: ubuntu-22.04
    outputs:
      text: ${{ steps.version.outputs.text }}
      numeric: ${{ steps.version.outputs.numeric }}
      major: ${{ steps.process.outputs.major }}
      significant: ${{ steps.process.outputs.significant }}
      triple: ${{ steps.process.outputs.triple }}
      preRelease: ${{ steps.process.outputs.preRelease }}
    steps:
      - name: Get tags
        id: tag
        if: |
            github.ref_type == 'tag' &&
            startsWith(github.ref_name, 'v')
        run: |
          echo "v=${refName:1}" >> $GITHUB_OUTPUT
        env:
          refName: ${{ github.ref_name }}

      - name: Get input
        id: given
        if: |
            startsWith(inputs.version, 'v')
        run: |
          echo "v=${input:1}" >> $GITHUB_OUTPUT
        env:
          input: ${{ inputs.version }}

      - name: Get Version
        id: version
        if: |
            steps.given.outputs.v != '' ||
            steps.tag.outputs.v != ''
        run: |
          numericVersion=${tag}
          if [ "$given" != "" ] ; then
            if [ "$tag" != "" ] ; then
              echo "Tag/Input mismatch.  Using input ($given) not tag ($tag)."
            fi
            numericVersion=${given}
          fi
          echo "numeric=$numericVersion" >> $GITHUB_OUTPUT
          echo "text=v$numericVersion" >> $GITHUB_OUTPUT
          echo "Core version is $numericVersion"
        env:
          given: ${{ steps.given.outputs.v }}
          tag: ${{ steps.tag.outputs.v }}

      - name: Extended Processing
        id: process
        if: |
            steps.version.outputs.numeric != ''
        run: |
          preRelease=false
          arrayVersion=(${numericVersion//./ })
          majorVersion=${arrayVersion[0]}
          significantVersion=""
          tripleVersion=""
          dot=""
          digit=0
          number='^[0-9]+$'
          for v in "${arrayVersion[@]}" ; do
            if ! [[ "$v" =~ $number ]] ; then
              echo "Digit $digit ($v) is not entirely numeric."
              if [ $digit -eq 2 ] ; then
                preFlags=(pre rc a alpha b beta)
                for flag in ${preFlags[@]} ; do
                  if [[ "$v" =~ $flag ]] ; then
                    preRelease=true
                  fi
                done
              fi
              if [ "$preRelease" != "true" ] ; then
                echo "Digit $digit ($v) is not a number (from v$numericVersion)."
                exit 1
              fi
            fi
            if [ $digit -le 2 ] || [ $v -gt 0 ] ; then 
              significantVersion=${significantVersion}${dot}${v}
              if [ $digit -le 2 ] ; then
                tripleVersion=${tripleVersion}${dot}${v}
              fi
              dot="."
            fi
            digit=$((digit+1))
          done
          for (( i=$digit; i<2; i++ )) ; do
            tripleVersion=${tripleVersion}.0
          done
          echo Significant $significantVersion, Major $majorVersion, pre=$preRelease ... minor ${arrayVersion[1]} patch ${arrayVersion[2]} package ${arrayVersion[3]}
          echo "major=$majorVersion" >> $GITHUB_OUTPUT
          echo "significant=$significantVersion" >> $GITHUB_OUTPUT
          echo "triple=$tripleVersion" >> $GITHUB_OUTPUT
          echo "preRelease=$preRelease" >> $GITHUB_OUTPUT
        env:
          numericVersion: ${{ steps.version.outputs.numeric }}

      - name: Bad Version
        if: |
            inputs.strict == 'true' &&
            ( steps.version.outputs.numeric == '' ||
              steps.process.outputs.preRelease == ''
            )
        run: |
          echo "The version tag should be in the format v22.09.6, v22.09.6rc1 or similar."
          exit 1
